spring.application.name=aws-microservice
server.port=8081

# Set the active profile to dev for EC2 deployment
spring.profiles.active=dev

# AWS S3 Configuration
aws.s3.bucket-name=praboss1234
aws.access-key=YOUR_AWS_ACCESS_KEY
aws.secret-key=YOUR_AWS_SECRET_KEY

# Database Configuration
spring.datasource.url=jdbc:mysql://database-1.ctkiak6mi49z.eu-north-1.rds.amazonaws.com:3306/postgres?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=admin1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
